import { Book } from '../interfaces/book-interface';

export const booksMock: Book[] = [
  {
    id: 8,
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    price: 18.5,
    discountPercentage: 20,
    category: 'Literatura',
    imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8437604885.01.L.jpg',
    year: 1967,
  },
  {
    id: 9,
    title: 'El Quijote de la Mancha',
    author: 'Miguel de Cervantes',
    price: 22.95,
    category: 'Clásicos',
    imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8424116859.01.L.jpg',
    year: 1605,
  },
  // {
  //   id: 3,
  //   title: 'La Casa de los Espíritus',
  //   author: 'Isabel Allende',
  //   price: 16.75,
  //   category: 'Literatura',
  //   imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8497592441.01.L.jpg',
  //   year: 1982,
  // },
  // {
  //   id: 4,
  //   title: 'Rayuela',
  //   author: 'Julio Cortázar',
  //   price: 19.99,
  //   category: 'Literatura',
  //   imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8437604737.01.L.jpg',
  //   year: 1963,
  // },
  // {
  //   id: 5,
  //   title: 'El Aleph',
  //   author: 'Jorge Luis Borges',
  //   price: 15.25,
  //   category: 'Cuentos',
  //   imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8420633801.01.L.jpg',
  //   year: 1949,
  // },
  // {
  //   id: 6,
  //   title: 'Pedro Páramo',
  //   author: 'Juan Rulfo',
  //   price: 14.5,
  //   category: 'Literatura',
  //   imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8437604729.01.L.jpg',
  //   year: 1955,
  // },
  // {
  //   id: 7,
  //   title: 'Como agua para chocolate',
  //   author: 'Laura Esquivel',
  //   price: 17.8,
  //   category: 'Romance',
  //   imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8497592468.01.L.jpg',
  //   year: 1989,
  // },
  // {
  //   id: 8,
  //   title: 'La fiesta del chivo',
  //   author: 'Mario Vargas Llosa',
  //   price: 21.25,
  //   category: 'Historia',
  //   imageUrl: 'https://images-na.ssl-images-amazon.com/images/P/8420467251.01.L.jpg',
  //   year: 2000,
  // },
];
